### ISSUE TITLE
Alpha Milestone

### ISSUE THREAD

**Issue by BenderBlog** [BenderBlog/watermeter#2]
Things to do before alpha:

- [x] Class table window should look nearly identical as [Timetable](https://github.com/zfman/TimetableView).
- [x] Migrate to Material 3.
- [x] Examination time window.
- [x] Money on School Identity Card and check the record.
- [x] Local only mode / ids broken mode.
- [x] Electricity.
- [x] Score window.
- [x] XDU Planet
- [x] Library Check
- [x] Tidy up the route & A new homepage.
